export const FEEDS_FETCH_BEGIN = 'FEEDS_FETCH_BEGIN';
export const FEEDS_FETCH_INVALIDATE = 'FEEDS_FETCH_INVALIDATE';
export const FEEDS_FETCH_COMPLETE = 'FEEDS_FETCH_COMPLETE';
export const FEEDS_UPDATE = 'FEEDS_UPDATE';

export const FEED_CREATE = 'FEED_CREATE';
export const FEED_SELECT = 'FEED_SELECT';
export const FEED_ADD = 'FEED_ADD';
export const FEED_REMOVE = 'FEED_REMOVE';
export const FEED_EDIT_BEGIN = 'FEED_EDIT_BEGIN';
export const FEED_EDIT_COMPLETE = 'FEED_EDIT_COMPLETE';
export const FEED_ADD_ITEM = 'FEED_ADD_ITEM';
export const FEED_REMOVE_ITEM = 'FEED_REMOVE_ITEM';
export const FEED_SAVE_BEGIN = 'FEED_SAVE_BEGIN';
export const FEED_SAVE_COMPLETE = 'FEED_SAVE_COMPLETE`';
