export const GET_FEEDS_BEGIN = 'GET_FEEDS_BEGIN';
export const GET_FEEDS_INVALIDATE = 'GET_FEEDS_INVALIDATE';
export const GET_FEEDS_COMPLETED = 'GET_FEEDS_COMPLETED';

export const GET_FEED = 'GET_FEED';
export const ADD_FEED = 'ADD_FEED';
export const REMOVE_FEED = 'REMOVE_FEED';
export const SAVE_FEED = 'SAVE_FEED';
export const ADD_FEED_ITEM = 'ADD_FEED_ITEM';
export const REMOVE_FEED_ITEM = 'REMOVE_FEED_ITEM';
export const SAVE_FEED_ITEM = 'SAVE_FEED_ITEM';
