api:
  build: .
  ports:
  - "3456:3456"
  links:
  - redis
  - postgres
  environment: &environment
    ENV: dev
    API_PUBLIC_URL: "http://192.168.99.100:3456/api/v1"
    BITLY_API_KEY: "c7399c2f47f02017fb3f02f46f10ce1099317d8a"
redis:
  image: redis:3.0
  ports:
  - "6379:6379"

postgres:
  build: db
  ports:
  - "5432:5432"
  environment:
    ENV: dev
    DB_NAME: 'myfeeds_dev'
    DB_USER: 'myfeeds_dev'
    DB_PASSWD: 'kWd2XdJUhGPRo3XlxUcvYJAebCZvbieM'
