api:
  build: .
  ports:
  - "3456:3456"
  links:
  - redis
  - postgres
  environment: &environment
    ENV: dev
    API_PUBLIC_URL: "192.168.99.100"
    DB_NAME: 'myfeeds_dev'
    DB_USER: 'myfeeds_dev'
    DB_PASSWD: 'myfeeds_dev_secret'

redis:
  image: redis:3.0

postgres:
  build: db
  ports:
  - "5432:5432"
  volumes:
  - ~/.docker-data/myfeeds/postgresql/data:/var/lib/postgresql/data
  environment: *environment
